// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAipsxuVBPlODQZajPhfEHA8sU1GSryp2g',
    appId: '1:779110394031:web:3d2eee920d8d5866b8cc5a',
    messagingSenderId: '779110394031',
    projectId: 'unyt-a2c51',
    authDomain: 'unyt-a2c51.firebaseapp.com',
    storageBucket: 'unyt-a2c51.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAjYqKdFyj2FQ-0JEYrnSiEqJgV_n8SSM',
    appId: '1:779110394031:android:3edeaaaa2fe238e7b8cc5a',
    messagingSenderId: '779110394031',
    projectId: 'unyt-a2c51',
    storageBucket: 'unyt-a2c51.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAipsxuVBPlODQZajPhfEHA8sU1GSryp2g',
    appId: '1:779110394031:web:ad80fad5f1df02efb8cc5a',
    messagingSenderId: '779110394031',
    projectId: 'unyt-a2c51',
    authDomain: 'unyt-a2c51.firebaseapp.com',
    storageBucket: 'unyt-a2c51.firebasestorage.app',
  );
}
